import { ThemeProvider, CssBaseline } from '@mui/material';
import { darkTheme } from "../lib/shared/theme";
import './globals.css';
import { Roboto } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
});

// TODO: set title and description for metadata on pages
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <body className={roboto.className}>
          {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
