name: 'Track-It build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install package dependencies
        run: npm install

      - name: Check linting and formatting
        run: npm run lint

      - name: Create test build
        run: npm run build
        env:
          NEXT_PUBLIC_THE_MOVIE_DB_API_KEY: ${{secrets.MOVIE_DB_API_KEY}}
          NEXT_PUBLIC_OMDB_API_KEY: ${{secrets.OMDB_API_KEY}}
          NEXT_PUBLIC_FF_API_KEY: ${{secrets.FF_API_KEY}}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
          NEXT_PUBLIC_THE_MOVIE_DB_BASE_URL: ${{secrets.THE_MOVIE_DB_BASE_URL}}
          FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
